version: "2.1"
services:
  couchdb:
    image: couchdb
    container_name: obsidian-livesync
    #user: 1000:1000
    environment:
      - COUCHDB_USER=${COUCHDB_USER} # enter the desired CouchDB admin username
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD} # enter the desired CouchDB admin password
    volumes:
      - ./data:/opt/couchdb/data
      - ./conf/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - '5984'
    restart: unless-stopped
    labels:
      - 'caddy_0=https://obsidian-sync.milan.place'
      #Block /
      - 'caddy_0.handle_path=/*'
      - 'caddy_0.handle_path.0_respond="\"\" 403"'
      - 'caddy_0.handle_path.0_header.-Server=""'
      #Secret (?) url haha
      - 'caddy_0.handle_path_1=/e=_/*'
      - 'caddy_0.handle_path_1.reverse_proxy="{{upstreams 5984}}"'
      #- 'caddy_ingress_network=ukwkwsk'
