version: "2.1"
services:
  couchdb:
    image: couchdb
    container_name: obsidian-livesync
    user: 1000:1000
    environment:
      - COUCHDB_USER=${COUCHDB_USER} # enter the desired CouchDB admin username
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD} # enter the desired CouchDB admin password
    volumes:
      - ${PWD}/data:/opt/couchdb/data
      - ${PWD}/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: unless-stopped
